### ISSUE TITLE
Readme.md code fails when using tensorflow==2.0.0 but works with tensorflow==2.3.1

### ISSUE THREAD

**Issue by bluelight773** [idealo/image-super-resolution#156]
If I install ISR using `pip install ISR`, then try to run code per the readme.md, I get errors. For instance, attempting to run the following:
```
from ISR.models import RDN
rdn = RDN(weights='psnr-small')
```
produces an error regarding failure to `.decode('utf8')`

However, if I force the installation of tensorflow==2.3.1 rather than the required tensorflow==2.0.0, I don't get any errors and I'm able to run the readme.md code. As suggested by https://github.com/idealo/image-super-resolution/issues/126, others seem to be having similar issues that are resolved by using the most recent tensorflow version.

**Comment by andre-fu** [comment]
Hello What was the solution to the 

`AttributeError: 'str' object has no attribute 'decode'` error? How did you fix the `.decode('utf8')` issue?
